vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.opt.backup = false
vim.opt.clipboard = 'unnamedplus'
vim.opt.cmdheight = 1
vim.opt.completeopt = { 'menuone', 'noselect' }
vim.opt.fileencoding = 'utf-8'
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.mouse = 'a'
vim.opt.showmode = false -- Lualine takes care of this
vim.opt.showtabline = 1
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.termguicolors = true
vim.opt.timeoutlen = 300
vim.opt.undofile = true
vim.opt.updatetime = 250
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.cursorline = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.showcmd = false
vim.opt.numberwidth = 4
vim.opt.signcolumn = 'yes'
vim.opt.scrolloff = 5
vim.opt.sidescrolloff = 5
vim.opt.wrap = false
vim.opt.linebreak = true
vim.opt.foldmethod = 'indent'
vim.opt.foldenable = false
vim.opt.guifont = 'IosevkaTerm Nerd Font:h18'
vim.g.doge_enable_mappings = 0 -- vim plugin setting
vim.opt.wildignore:append { '**/node_modules/**', '**/.git/**', '**/dist/**' }
